# Site settings
title: IEEE International Conference on Software Maintenance and Engineering (ICSME)
email: icsme-sc@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  Official website of the IEEE International Conference on Software Maintenance and Engineering (ICSME)
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: IEEEICSME
github_username:  IEEEICSME

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  past:
    output: true
    permalink: /past/:path/
  documents:
    output: true
    permalink: /documents/:path/
  sc:
    output: true
    permalink: /sc/:path/


